name: KingGame
options:
  bundleIdPrefix: com.igurocak
targets:
  KingGame:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - App
      - Engine
      - Models
      - ViewModels
      - Views
    settings:
      base:
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: Y87LV5JK4T
        INFOPLIST_KEY_CFBundleDisplayName: "Kralın 20 Eli"
